package com.drools.demo.point  
  
import com.test.drools.PointDomain;  
  
rule subBackNumsPoint  
    // 发生退货，扣减10分  
    salience 10  
    lock-on-active true  
    when  
        $pointDomain : PointDomain(backNums >= 1)  
    then  
        System.out.println("subBackNumsPoint");   
end  
  
rule subBackMondyPoint  
    // 退货金额大于100，扣减100分  
    salience 9  
    lock-on-active true  
    when  
        $pointDomain : PointDomain(backMondy >= 100)  
    then  
       System.out.println("subBackMondyPoint"); 
end  